name: 'Image Compressor'
author: 'chabad360'
description: 'Compress Images'

inputs:
  githubToken:
    description: 'GitHub Token (required for PR testing)'
    required: false

  jpegQuality:
    description: 'JPEG quality level'
    required: false
    default: 80

  pngQuality:
    description: 'PNG quality level'
    required: false
    default: 80

  webpQuality:
    description: 'WEBP quality level'
    required: false
    default: 80

  ignorePaths:
    description: 'Paths to ignore during search'
    required: false
    default: "nodemodules/**"

runs:
  using: 'docker'
  image: 'Dockerfile'
#  image: 'docker://calibreapp/image-action' 