name: 'images action'
author: 'chabad360'
description: "compress images"

inputs:
  jpegQuality:
    description: "JPEG quality level"
    required: false
    default: 80

  pngQuality:
    description: "PNG quality level"
    required: false
    default: 80

  webpQuality:
    description: "WEBP quality level"
    required: false
    default: 80

  ignorePaths:
    description: "Paths to ignore during search"
    required: false
    default: "node_modules/**"
    
runs:
  using: 'docker'
  image: 'Dockerfile'