name: "\U0001F41B Bug report"
description: "Found an issue? File a bug report to help us improve this project for everyone."
title: "[Bug] Bug description"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        👋🏻 Hi there! This template will help you file a complete bug report, so one of the project maintainers can triage and respond to it promptly.
  - type: markdown
    attributes:
      value: | 
        Please fill relevant sections below. Thank you for helping us improve this project! ⚡️
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is. Include relevant operating system, browser and other environment information.
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: How To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: "1. Go to '...'
                    2. Click on '....'
                    3. Scroll down to '....'
                    4. See error"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: textarea
    id: output-log
    attributes:
      label: Relevant Log Output
      description: Add any browser console errors or terminal logs. No need for backticks here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/calibreapp/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project’s Code of Conduct
          required: true